### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by tschm**
Make sure your name is in there...

### CODE REVIEW

**Comment by tschm** [comment]
recheck

**Comment by akshayka** [comment]
Thanks @tschm!

I'm looking into this. My current understanding is that the Appendix is not actually part of the license, but instead a recommendation to include the boilerplate below it as the header of individual files. I got this understanding from

https://www.apache.org/licenses/LICENSE-2.0.html#apply

This interpretation is congruent with how official Apache projects are set up, e.g. Apache Spark: https://github.com/apache/spark/blob/master/LICENSE

We have some automation that prepends a copyright notice but not the appendix/header. Perhaps we should do that ...

**Comment by tschm** [comment]
@akshayka you might be perfectly right. But a copyright notice in each *.py file could be a bit too much...

**Comment by akshayka** [comment]
Closing as per our discussion. We should perhaps follow up and prepend the license notice to each file ...

**Pull request closed without merging**
