### PR TITLE
added skvideo module name (scikit-video package)

### PR DESCRIPTION
**Pull request by simonmaris**
Added resolver from skvideo to scikit-video.

@akshayka

### CODE REVIEW

**Review by mscolnick — APPROVED** [review]
thanks for the contribution!

**Comment by mscolnick** [comment]
@simonmaris - do you mind responding with the CLA signature?

**Comment by simonmaris** [comment]
I have read the CLA Document and I hereby sign the CLA

recheck.

**Comment by simonmaris** [comment]
recheck

**Pull request merged**
