### PR TITLE
Add mapping for quaternion -> numpy-quaternion

### PR DESCRIPTION
**Pull request by moble**
## 📝 Summary

This adds a mapping for the `quaternion` package, which is named `numpy-quaternion` on PyPI.

## 🔍 Description of Changes

Just added the key:value pair to the `module_name_to_pypi_name` dict.  I'm hoping a test is not needed for such a simple change, though I have tried it locally and verified that it works by automatically installing `numpy-quaternion`.

## 📋 Checklist

- [X] I have read the [contributor guidelines]([[https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md]]).
- [ ] I have added tests for the changes made.
- [X] I have run the code and verified that it works as expected.

## 📜 Reviewers

@mscolnick

### CODE REVIEW

**Comment by moble** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by moble** [comment]
recheck

**Review by akshayka — APPROVED** [review]
While there is also a package called quaternion, it looks like numpy-quaternion is more commonly used and more actively developed.

So, looks good, thank you!

**Comment by moble** [comment]
> While there is also a package called quaternion, it looks like numpy-quaternion is more commonly used and more actively developed.

And, in fact, importing that other package requires `import Quaternion`, rather than `import quaternion`, so even though the default mapping would `pip install quaternion`, but then error when trying to actually import it.  Gotta love PyPI!

**Pull request merged**
