### PR TITLE
Introducing marimo Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [marimo Guru](https://gurubase.io/g/marimo) to Gurubase. marimo Guru uses the data from this repo and data from the [docs](https://docs.marimo.io) to answer questions by leveraging the LLM.

In this PR, I showcased the "marimo Guru", which highlights that marimo now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable marimo Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by kursataktas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by kursataktas** [comment]
recheck

**Comment by akshayka** [comment]
> I wanted to update you that I've manually added the [marimo Guru](https://gurubase.io/g/marimo) to Gurubase.

Awesome!

> In this PR, I showcased the "marimo Guru", which highlights that marimo now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

The README isn't the right place for this. We could potentially add a "projects using marimo" section to docs.marimo.io, and have a link to guru there

**Comment by akshayka** [comment]
@kursataktas , I've added your project to awesome marimo (https://github.com/marimo-team/awesome-marimo/blob/main/README.md). Thanks for letting us know about it!

**Comment by kursataktas** [comment]
This is great @akshayka Thank you!

**Pull request closed without merging**
