### PR TITLE
feat: custom ai assist rules

### PR DESCRIPTION
**Pull request by mscolnick**
### Setup 
Screenshot 2024-10-11 at 6 22 27 AM
Screenshot 2024-10-11 at 6 31 53 AM

## Result

Screenshot 2024-10-11 at 6 30 47 AM

### CODE REVIEW

**Review by akshayka — APPROVED** [review]

**Comment by mscolnick** [comment]
@Haleshot is this for mo.ui.chat or the embedded ai assist?

If that latter, can we improve the system chat for everyone instead of customizing it? We already allow customization through these rules.

**Comment by Haleshot** [comment]
> @Haleshot is this for mo.ui.chat or the embedded ai assist?
> 
> If that latter, can we improve the system chat for everyone instead of customizing it? We already allow customization through these rules.

I was thinking about the mo.ui.chat feature. We have a settings toggle in the left side (for temperature, top p, etc. parameter controls); thought we could have a `tab` like feature (like `mo.ui.tabs`) where one tab is devoted to parameters like that and one for the system prompt for the chat to follow when replying to the user.

Do you mean like a standard system prompt that is defined (default) for the `embedded AI assist` (like you have the placeholder now)?

**Comment by Haleshot** [comment]
Let me know if this would be good to work on.

**Comment by mscolnick** [comment]
@Haleshot all the models in mo.ai.llm take in system prompt, so it is configurable there.

**Pull request merged**
