### PR TITLE
Fix for Incorrect OS Version Displayed for Windows 11 in `marimo env` Command

### LINKED ISSUE #1409: Incorrect OS Version Displayed for Windows 11 in `marimo env` Command
### Describe the bug

The `marimo env` command incorrectly displays the OS version as "10" for Windows 11 systems. This issue arises because the `platform.release()` function relies on the version of the `kernel32.dll` file, which remains unchanged between Windows 10 and Windows 11. As a result, the actual Windows version is not accurately reflected.

### Workaround or Plan to Submit a PR

I have identified a solution that involves using `sys.getwindowsversion().build` to determine if the OS is Windows 11 and updating the `OS Version` field accordingly. I am planning to submit a PR with the necessary changes to fix this issue.

### Stack Trace or Screenshots

N/A

---

Here’s the problematic output:

```json
{
  "marimo": "0.3.7",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "Python Version": "3.11.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v18.17.0"
  },
  "Requirements": {
    "click": "8.1.6",
    "importlib-resources": "6.3.2",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.15.1",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.3.0"
  }
}
```

The `OS Version` should reflect "11" for Windows 11 systems instead of "10".

### Environment

```json
{
  "marimo": "0.3.7",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "Python Version": "3.11.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v18.17.0"
  },
  "Requirements": {
    "click": "8.1.6",
    "importlib-resources": "6.3.2",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.15.1",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.3.0"
  }
}
```

### Code to reproduce

To reproduce the issue, simply run the `marimo env` command on a Windows 11 machine. The command faces issues in displaying when the OS version is 11.

Alternatively, you can use the following minimal reproducible example to observe the issue:

```python
# Example code to reproduce the issue

import platform

def get_system_info():
    info = {
        "OS": platform.system(),
        "OS Version": platform.release(),  # This will show "10" on Windows 11
        "Processor": platform.processor(),
        "Python Version": platform.python_version(),
    }
    return info

if __name__ == "__main__":
    system_info = get_system_info()
    print(system_info)
```

Running this code on a Windows 11 machine will display the incorrect OS version:

```sh
python example.py
```

Expected Output (on Windows 11):
```json
{
  "OS": "Windows",
  "OS Version": "10",  # Incorrectly shows "10" instead of "11"
  "Processor": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "Python Version": "3.11.4"
}
```

### PR DESCRIPTION
**Pull request by Haleshot**
Fixes #1409

### PR Title
Fix OS Version Display for Windows 11 in `marimo env` Command

### Description
The current implementation of the `get_system_info` function in `envinfo.py` incorrectly retrieves the OS version using `platform.release()`, which does not differentiate between Windows 10 and Windows 11.. This PR addresses this issue by implementing a check for Windows 11 using `sys.getwindowsversion().build` and updating the `OS Version` field accordingly.
More information on this [here](https://learn.microsoft.com/en-us/windows/release-health/windows11-release-information#windows-11-release-history).

### Changes Made
- Introduced a new function `is_win11()` to determine if the OS is Windows 11 based on the build number (`sys.getwindowsversion().build >= 22000`).
- Modified `get_system_info` to use the `is_win11()` function to set the `OS Version` to "11" if running on Windows 11.

### Example Output
Before PR:
```json
{
  "marimo": "0.3.7",
  "OS": "Windows",
  "OS Version": "10",
  "Processor": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "Python Version": "3.11.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v18.17.0"
  },
  "Requirements": {
    "click": "8.1.6",
    "importlib-resources": "6.3.2",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.15.1",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.3.0"
  }
}
```

After PR:
```json
{
  "marimo": "0.3.7", 
  "OS": "Windows",
  "OS Version": "11",
  "Processor": "AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD",
  "Python Version": "3.11.4",
  "Binaries": {
    "Browser": "--",
    "Node": "v18.17.0"
  },
  "Requirements": {
    "click": "8.1.6",
    "importlib-resources": "6.3.2",
    "jedi": "0.19.0",
    "markdown": "3.6",
    "pymdown-extensions": "10.7.1",
    "pygments": "2.15.1",
    "tomlkit": "0.12.4",
    "uvicorn": "0.29.0",
    "starlette": "0.37.2",
    "websocket": "missing",
    "typing-extensions": "4.10.0",
    "black": "24.3.0"
  }
}
```

### Checklist
- [x] Implemented `is_win11()` function to correctly identify Windows 11.
- [x] Updated `get_system_info` to use `is_win11()` for determining the OS version.
- [x] Tested on Windows 11 to ensure correct functionality.

### CODE REVIEW

**Comment by mscolnick** [comment]
@Haleshot thanks for the contribution! i think some of the code-suggestions would be good to add, and there is a lint error (`make py-check` fixes this, and we have `pre-commit` too if you want to use that)

**Comment by Haleshot** [comment]
recheck

**Comment by mscolnick** [comment]
@Haleshot `main` is currently failing so ill force merge, but you'll still need to sign the CLA aggrement (by commenting on this PR)

**Comment by Haleshot** [comment]
> @Haleshot `main` is currently failing so ill force merge, but you'll still need to sign the CLA aggrement (by commenting on this PR)

Thanks. I seem to have combined another PR (didn't pull before committing) and even that commit got added here. Looking into removing that commit. 

Apologize for the inconvenience caused.

**Comment by Haleshot** [comment]
@mscolnick Hope it's alright now. Reverted the commit and now made the final changes. Do let me know if it's alright/anything to be done from my side.

**Comment by mscolnick** [comment]
@Haleshot you'll still need to sign the CLA - by pasting the text from above (it should be the first message in this thread)

**Comment by Haleshot** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Haleshot** [comment]
Added PR template in the same. Fixes #1413

**Review by mscolnick — DISMISSED** [review]

**Comment by gvarnavi** [comment]
@mscolnick @akshayka This PR seems to have [reverted](https://github.com/marimo-team/marimo/commit/43a07c4795c3c74cc3859503bde81577ba310821#diff-d058981dfd1dcb84c82571e955b1eca3caf5d68224840b5131ebf446b77cf2f8) the new MarimoIslandGenerator features.

**Comment by mscolnick** [comment]
@gvarnavi it looks like it did for a commit, but then that was unreverted. The PR diff still looks fine. Is the new feature not in the published version?

**Comment by gvarnavi** [comment]
It's not, no --that's how I caught it.
Here's the [file history](https://github.com/marimo-team/marimo/commits/main/marimo/_islands) in `main` which shows that this was the last commit. Note it also affected [marimo/_server/export/__init__.py](https://github.com/marimo-team/marimo/commits/main/marimo/_server/export/__init__.py).

**Comment by akshayka** [comment]
Weird .. I can revert it.

**Comment by akshayka** [comment]
> It's not, no --that's how I caught it. Here's the [file history](https://github.com/marimo-team/marimo/commits/main/marimo/_islands) in `main` which shows that this was the last commit. Note it also affected [marimo/_server/export/**init**.py](https://github.com/marimo-team/marimo/commits/main/marimo/_server/export/__init__.py).

Let me know if #1471 looks good

**Comment by Haleshot** [comment]
Apologize for the above confusion and inconvenience caused due to this PR. Not sure how my commits got cluttered in the first place; learning to be more comfortable with using just git CLI than the VS integration.

Hope to be more careful when contributing next time.

**Comment by gvarnavi** [comment]
Oh no worries at all -- git merging can often feel like dark magic!

**Pull request merged**
