### PR TITLE
tidy: Tweaks to enable pytest on marimo nbs

### PR DESCRIPTION
**Pull request by dmadisetti**
I was really interested in having tests in notebooks (re discussion yesterday), so I played around with it a tiny bit this afternoon. As is, pytest does not work out of the box since:
 1. the wrapped functions become Cell instances
 2. coroutine detection through the `_is_coroutine` spec should be as an attribute

This change enables both of these minor adjustments. Now, pytest will pick up
marimo `test_*` functions, but they will fail since directly invoking a cell is
currently not allowed. I put in a little unit test to fight against a possible
regression until such time when a top level fn spec is enabled (see #2293).

@akshayka OR @mscolnick

### CODE REVIEW

**Review by mscolnick — DISMISSED** [review]
wow this is a cool awesome find. would be amazing to support `test_` cells

**Review by akshayka — COMMENTED** [review]
Thanks! The cell execution API could be improved. Could consider lifting the restriction on calling cells directly, just found it weird because you can call them without passing any of what appear to be the required positional args.

Noticed a test is failing?

**Comment by dmadisetti** [comment]
Yes, I think the test is related- but not totally obvious how. Digging in now.

> Could consider lifting the restriction on calling cells directly, just found it weird because you can call them without passing any of what appear to be the required positional args.

I think it might be useful to just allow a direct call if the correct args are passed in, but require "run" if used in the context of the notebook.

**Comment by akshayka** [comment]
> I think it might be useful to just allow a direct call if the correct args are passed in,

In the case of `pytest`, wouldn't the framework call the cell without arguments, relying on marimo to compute the ancestors instead?

**Pull request merged**
