### PR TITLE
Update version in Dockerfile

### PR DESCRIPTION
**Pull request by eracle**

### CODE REVIEW

**Review by mscolnick — APPROVED** [review]

**Comment by mscolnick** [comment]
@eracle - thanks for the contribution. 

just so you know, you can also pass `--build-arg marimo_version=x.x.x` into the Dockerfile as a [build arg](https://docs.docker.com/build/building/variables/)

**Comment by mscolnick** [comment]
Closing due to inactivity

**Comment by mscolnick** [comment]
Sorry @eracle, it was missing the CLA agreement

**Comment by mscolnick** [comment]
You just need to reply with "I have read the CLA Document and I hereby sign the CLA"

**Comment by eracle** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mscolnick** [comment]
Recheck

**Pull request merged**
