### PR TITLE
fix: altair crashing when using special characters in columns

### PR DESCRIPTION
**Pull request by mscolnick**
Fixes: #1530

We are able to escape some characters like:
```
        "[0]": "brackets",
        ":": "colon",
        ".": "period",
        "\\": "backslash",
```

For backslashes, single, and double quotes, its harder to escape since not only do the columns need to be escaped, but so does the keys of the data, and i couldnt figure out a way to do this cleanly. So instead we show a clear warning for them to rename.

### CODE REVIEW

**Comment by dmadisetti** [comment]
I think I got the latest commit?

image

offending xlsx attached
[xss.xlsx](https://github.com/user-attachments/files/15507694/xss.xlsx)


but works with the actual weird taskmaster data I found!

**Comment by mscolnick** [comment]
I can handle that, thanks for breaking it ha

**Comment by dmadisetti** [comment]
Hmm, I thought so. Will try again and then swap browser if it persists

**Comment by mscolnick** [comment]
I guess looking at your screenshot, I can see the proper sanitization

**Comment by dmadisetti** [comment]
Happens in chrome too, I have to click the accordion though. I'm getting this error on the dev server too:

<details><summary>react trace</summary>

```txt
The above error occurred in the <ForwardRef> component:

be<@http://3000.port.ave/node_modules/.vite/deps/cmdk.js?v=b5b41a36:1869:36
div
_c2@http://3000.port.ave/src/components/ui/command.tsx:54:59
div
div
le<@http://3000.port.ave/node_modules/.vite/deps/cmdk.js?v=b5b41a36:1669:13
Command<@http://3000.port.ave/src/components/ui/command.tsx:17:48
div
DataSourcesPanel@http://3000.port.ave/src/components/editor/chrome/panels/datasources-panel.tsx:34:49
div
Suspense
span
div
PanelWithForwardedRef@http://3000.port.ave/node_modules/.vite/deps/react-resizable-panels.js?v=b5b41a36:39:31
forwardRef(Panel)
div
PanelGroupWithForwardedRef@http://3000.port.ave/node_modules/.vite/deps/react-resizable-panels.js?v=b5b41a36:1401:36
forwardRef(PanelGroup)
div
AppChrome@http://3000.port.ave/src/components/editor/chrome/wrapper/app-chrome.tsx:31:26
EditPage
div
CssVariables@http://3000.port.ave/src/theme/ThemeProvider.tsx:38:29
ModalProvider@http://3000.port.ave/src/components/modal/ImperativeModal.tsx:22:37
Provider@http://3000.port.ave/node_modules/.vite/deps/@marimo-team_react-slotz.js?v=b5b41a36:214:16
DayPickerProvider@http://3000.port.ave/node_modules/.vite/deps/react-day-picker.js?v=b5b41a36:28185:22
Provider@http://3000.port.ave/node_modules/.vite/deps/chunk-A74ZBUGF.js?v=b5b41a36:46:47
$a093c7e1ec25a057$export$f78649fb9ca566b8@http://3000.port.ave/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=b5b41a36:66:160
Suspense
ErrorBoundary@http://3000.port.ave/node_modules/.vite/deps/react-error-boundary.js?v=b5b41a36:18:5
ErrorBoundary@http://3000.port.ave/src/components/editor/boundary/ErrorBoundary.tsx:16:9
Providers<@http://3000.port.ave/src/core/MarimoApp.tsx:108:42
_c6<@http://3000.port.ave/src/core/MarimoApp.tsx:48:26
_c<@http://3000.port.ave/src/theme/ThemeProvider.tsx:15:64
Provider@http://3000.port.ave/node_modules/.vite/deps/chunk-UTGSP66C.js?v=b5b41a36:626:16
```
</details>

**Review by akshayka — APPROVED** [review]

**Comment by akshayka** [comment]
LGTM but haven't tried the test data that you all are playing with, will let @dmadisetti review/approve

**Comment by mscolnick** [comment]
going to merge (since its an improvement) and then investigate the other bad characters

**Pull request merged**
