### PR TITLE
fix: islands render_html() head needs marimo tags

### PR DESCRIPTION
**Pull request by akshayka**
HTML generated with `MarimoIslandGenerator.from_file().render_html()` was failing to render because the frontend expects marimo-filename and marimo-mode tags to be present.

### CODE REVIEW

**Comment by dmadisetti** [comment]
So, this is actually due to a failing islands check. I put this in as a specific tag and we decided to revert it. 

Relevant: https://github.com/marimo-team/marimo/pull/1214

Revert: https://github.com/marimo-team/marimo/pull/1250

**Review by mscolnick — APPROVED** [review]

**Comment by mscolnick** [comment]
@dmadisetti i think your original solution works as well, and it is kinda nice adding this on the frontend than the backend so island consumers don't need to manually add these header tags if they arent using the python builder/geneartor

cc @akshayka

**Review by dmadisetti — APPROVED** [review]
Makes sense!

**Comment by akshayka** [comment]
I see two approvals, so I'll merge this :)

**Pull request merged**
