### PR TITLE
Add recipe for using lists for state

### PR DESCRIPTION
**Pull request by liquidcarbon**
## 📝 Summary

Example of using lists to hold initial state for triggering computation with a button

## 🔍 Description of Changes

Ideas from https://github.com/marimo-team/marimo/issues/2738#issuecomment-2491924652

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [x] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [x] I have added tests for the changes made.
- [x] I have run the code and verified that it works as expected.

### CODE REVIEW

**Comment by dmadisetti** [comment]
Hmm, read the thread- but I've always thought this was more of an antipattern. Thought on this?

```python
value = "No joke"

mo.stop(button.value is not None)
value = text.value.upper()

text, button, value
```

**Comment by liquidcarbon** [comment]
That way you'll never see the output, because button's initial value is False

**Comment by dmadisetti** [comment]
Woops! Yes. Edited for correctness.

But this gets around carrying state outside of `mo.State`

There's an experimental "Strict Execution" mode, where this will intentionally fail

**Comment by mscolnick** [comment]
i, too, think this is an anti-pattern because you are modifying state, which we are trying avoid mutations (similar to how [React works](https://react.dev/learn/updating-objects-in-state))

**Comment by akshayka** [comment]
I actually think stashing state in a non-reactive object (such as a Python list) can be simpler than using reactive state. I have noticed when people use reactive state, they have a difficult time reasoning about why cells are running and end up creating bugs that are hard to catch.

With non-reactive state, execution is still determined by the DAG. For this reason I personally prefer this pattern. I hadn't documented it because it does feel "advanced".

**Comment by akshayka** [comment]
The ideal recipe would be something like @dmadisetti's suggestion, though I think it doesn't do quite what @liquidcarbon is trying to do.

**Comment by liquidcarbon** [comment]
In @dmadisetti 's example the form will always reset to this initial value; it's fine in some cases, but I'd like to have a default, pre-populated UI with either 1) examples of how to use it, or 2) from query params

```
value = "No joke" 

mo.stop(not button.value)
value = text.value.upper()

text, button, value  # this is in the next cell, or UI will never show up because initial button.value is False
```

**Comment by akshayka** [comment]
@liquidcarbon, after reflecting I think this is too advanced or niche to add to the recipes — marimo already introduces so many new concepts, that I'm worried our users will get confused. Sorry to lead you astray.

Here is a simpler recipe that I believe does what you need, using `form()` and without using any kind of state.

If it does do what you need, want to change the recipe to this?

https://marimo.app/l/cdiigo

```python
import marimo

__generated_with = "0.9.21"
app = marimo.App(width="medium")


@app.cell
def __():
    import marimo as mo
    return (mo,)


@app.cell
def __(mo):
    form = mo.ui.text(label="Enter text").form(submit_button_label="capitalize", bordered=False)
    form
    return (form,)


@app.cell
def __(form):
    form.value.upper() if form.value is not None else "Here is my initial value"
    return


if __name__ == "__main__":
    app.run()
```

**Comment by liquidcarbon** [comment]
Sure, your call!  The code is findable in this PR.

I prefer the run_button over the form because it is more customizable (button label, hotkey), also: https://github.com/marimo-team/marimo/issues/2921

**Comment by akshayka** [comment]
@liquidcarbon, sorry I missed your edits. That recipe looks good to me, if you'd like to update the PR.

**Comment by liquidcarbon** [comment]
I'll open a new one.  This latest suggestion is a lot like [gradio examples](https://www.gradio.app/guides/more-on-examples); the original idea was quite different.

**Pull request closed without merging**
