### PR TITLE
Python 3.13

### PR DESCRIPTION
**Pull request by liquidcarbon**
Maybe it's too soon, but wanted to give it a shot.

### CODE REVIEW

**Comment by liquidcarbon** [comment]
Hatch doesn't support 3.13 yet, does it mean this PR should wait?

**Comment by mscolnick** [comment]
Yep we should wait until hatch supports this probably

**Comment by mscolnick** [comment]
@liquidcarbon - hatch now supports 3.13 , want to get this merged?

there are a few `"` autofixes, any chance we can revert those. i can look if I can prevent this in future with a pre-commit

**Comment by liquidcarbon** [comment]
not sure, maybe better off to start over, I doubt I covered everything and the business of merging such fast-moving main seems intimidating =)

**Comment by mscolnick** [comment]
closing as stale

**Pull request closed without merging**
