### PR TITLE
docs: fix typos and a broken link in PR template

### PR DESCRIPTION
**Pull request by Oreoxmt**
## 📝 Summary

Fix typos in the following documents:
- `docs/guides/ai_completion.md`
- `docs/recipes.md`
- `marimo/_plugins/ui/_impl/batch.py`

Fix a broken link `[contributor guidelines](../CONTRIBUTING.md)` in PR template

## 📋 Checklist

- [x] I have read the [contributor guidelines](../CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://discord.gg/JE7nhX6mD8), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [ ] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

**Comment by Oreoxmt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Oreoxmt** [comment]
recheck

**Comment by Oreoxmt** [comment]
@mscolnick Could you please help review this PR? Thanks

**Review by mscolnick — APPROVED** [review]
Thank you!

**Pull request merged**
