### PR TITLE
feat(runtime): add mode property to AppMeta

### LINKED ISSUE #2776: `marimo.app_meta().mode` Detection for Notebook Modes
### Description

Add a `marimo.app_meta().mode` attribute to detect the notebook mode, providing values like `Literal["edit", "app"]`.

This feature would allow notebooks to dynamically detect their operating mode—`edit`, `app`, etc—enabling more adaptable behavior and tailored displays based on the context. 

For example, users may want some contents to be displayed only in `edit` mode or `app` mode.

### Suggested solution

Add the `marimo.app_meta().mode` attribute.

### Alternative

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by metaboulie**
## 📝 Summary

fixes #2776 

Add ability to detect notebook mode (edit/run/script) through AppMeta. This allows code to conditionally execute based on the current mode without directly accessing the kernel context.

## 🔍 Description of Changes

- Add mode property to AppMeta class
- Add get_mode() utility function
- Add session_mode to KernelRuntimeContext
- Pass SessionMode through context initialization chain

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [x] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://marimo.io/discord?ref=pr), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [x] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

**Review by mscolnick — COMMENTED** [review]
Awesome work, 2 small comments:
- could we add a test 
- could we make the return type a Literal[] called AppMode

Let me know if you'd like me to handle these as well, happy to

**Comment by mscolnick** [comment]
Actually instead of creating an AppMode type, we can just inline the Literal[]

**Comment by metaboulie** [comment]
@mscolnick 
Tests added, but not sure whether they are comprehensive

**Review by mscolnick — APPROVED** [review]
great job @metaboulie

**Comment by metaboulie** [comment]
Thanks, I think I should add `mo.app_meta` to docs

**Comment by mscolnick** [comment]
@metaboulie, that would be great, thank you

**Pull request merged**
