### PR TITLE
Docs: Add guide to Codeium API key from VS Code

### PR DESCRIPTION
**Pull request by rparkr**
## 📝 Summary

Add a section to the docs on [AI Completion](https://docs.marimo.io/guides/editor_features/ai_completion.html#codeium-copilot) demonstrating how to obtain your Codeium API key using VS Code.

I wasn't able to successfully follow the instructions using the Chrome extension, but it was very easy to obtain the API key from the Codeium VS Code extension.

## 🔍 Description of Changes

Additions:
- [section](https://github.com/rparkr/marimo/blob/c5ba2fa30ce7c1d990d2a59551e53a83945b6001/docs/guides/editor_features/ai_completion.md#alternative-obtain-codeium-api-key-using-vs-code) in the docs on AI Completion
- 4 images in the _static directory:
  1. [docs-ai-completion-codeium-vscode.png](https://github.com/rparkr/marimo/blob/c5ba2fa30ce7c1d990d2a59551e53a83945b6001/docs/_static/docs-ai-completion-codeium-vscode.png)
  2. [docs-ai-completion-codeium-vscode-dark.png](https://github.com/rparkr/marimo/blob/c5ba2fa30ce7c1d990d2a59551e53a83945b6001/docs/_static/docs-ai-completion-codeium-vscode-dark.png)
  3. [docs-ai-completion-codeium-vscode-download-diagnostics.png](https://github.com/rparkr/marimo/blob/c5ba2fa30ce7c1d990d2a59551e53a83945b6001/docs/_static/docs-ai-completion-codeium-vscode-download-diagnostics.png)
  4. [docs-ai-completion-codeium-vscode-download-diagnostics-dark.png](https://github.com/rparkr/marimo/blob/c5ba2fa30ce7c1d990d2a59551e53a83945b6001/docs/_static/docs-ai-completion-codeium-vscode-download-diagnostics-dark.png)

There are two screenshots and two variants of each one (light and dark). I chose the light themed variant to match the theme of other screenshots on the site, but kept the dark ones in case they would be helpful for the docs' dark theme.

This section and the screenshots demonstrate how to obtain a Codeium API key using the Codeium VS Code extension. I added annotations to the screenshots to make them easy to follow and colored the annotations using marimo's green theme color.

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).
- [ ] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://discord.gg/JE7nhX6mD8), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [ ] I have added tests for the changes made.
- [ ] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

**Comment by rparkr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by akshayka — APPROVED** [review]
Thank you! I appreciate the attention to detail, down to the screenshots

**Comment by rparkr** [comment]
recheck

**Comment by rparkr** [comment]
Thanks @akshayka! Thank you for open-sourcing marimo -- it is absolutely incredible and I have really enjoyed using it.

**Pull request merged**
