### PR TITLE
Create README_Chinese.md. 

### PR DESCRIPTION
**Pull request by OOAAHH**
Provide Chinese annotations for the README.

## 📝 Summary

I added a README_chinese.md file, which is the localized Chinese version of the README.md.

## 🔍 Description of Changes

 I localized the entire text of the README file, using highly localized phrasing and language habits. This opens the door for Chinese users to better understand our project. China has a large community of Python users and developers, and this localization helps empower more users and developers who struggle with the difficulties and error-prone nature of Jupyter. It will assist them in focusing their attention on making new discoveries in their respective fields.

Additionally, as someone working in a research institution and involved in education, I hope this is a good starting point for me to introduce this excellent project to my students and colleagues. In the future, I plan to continue localizing other parts of our documentation and any unexpected sections. If you have similar ideas, I would be happy to collaborate, so feel free to reach out to me.

## 📋 Checklist

- [x] I have read the [contributor guidelines](https://github.com/marimo-team/marimo/blob/main/CONTRIBUTING.md).

- [x] For large changes, or changes that affect the public API: this change was discussed or approved through an issue, on [Discord](https://discord.gg/JE7nhX6mD8), or the community [discussions](https://github.com/marimo-team/marimo/discussions) (Please provide a link if applicable).
- [x] I have added tests for the changes made.
- [x] I have run the code and verified that it works as expected.

## 📜 Reviewers

@akshayka OR @mscolnick

### CODE REVIEW

**Comment by OOAAHH** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by OOAAHH** [comment]
recheck

**Comment by mscolnick** [comment]
thanks @OOAAHH! if we make changes to this, would you mind if we ping you for updates?

**Review by mscolnick — APPROVED** [review]

**Comment by OOAAHH** [comment]
Sure, I'd be happy to help with any updates. Feel free to ping me anytime.

**Pull request merged**
