### PR TITLE
mo.image(): visualize NumPy array, torch.tensor, scipy.sparse matrix

### PR DESCRIPTION
**Pull request by dmadisetti**
Closes out https://github.com/marimo-team/marimo/issues/629

Note that this plots the exact size, but it might be OK to sanity-check datasets or something.

I think this is a fair tradeoff though since you really should be using matplotlib if you want more control

### CODE REVIEW

**Comment by dmadisetti** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dmadisetti** [comment]
recheck

**Review by mscolnick — APPROVED** [review]
thanks for the contribution!

**Comment by dmadisetti** [comment]
No problem,


Looks like I'm missing the pillow and pillow type deps? Do those just go in project.toml?

**Comment by mscolnick** [comment]
@dmadisetti our type-checking is a bit finicky for optional dependencies. you'll want to add `# type: ignore[import-not-found,import-untyped,unused-ignore] # noqa: E501` in most places where you import optional deps

**Comment by dmadisetti** [comment]
The type checking and tests work locally, but I did have to install those

**Pull request merged**
