### PR TITLE
fix: Issue#574

### PR DESCRIPTION
**Pull request by metaboulie**
Adding an optional argument, `total` as suggested.

### CODE REVIEW

**Comment by metaboulie** [comment]
https://github.com/marimo-team/marimo/issues/574

**Comment by akshayka** [comment]
Thank you, @metaboulie! This looks good. Can you leave a comment for the CLA bot, with the text "I have read the CLA Document and I hereby sign the CLA"?

**Comment by metaboulie** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by metaboulie** [comment]
> Thank you, @metaboulie! This looks good. Can you leave a comment for the CLA bot, with the text "I have read the CLA Document and I hereby sign the CLA"?

Done that😃

**Pull request merged**
