### PR TITLE
Update refresh.py

### LINKED ISSUE #831: mo.ui.refresh_button doesn't exist
### Documentation is

- [ ] Missing
- [X] Outdated
- [X] Confusing
- [X] Not sure?

### Explain in Detail

Hello,

In https://docs.marimo.io/api/inputs/refresh.html#marimo.ui.refresh there is a code sample like so

  refresh_button = mo.ui.refresh_button(
      options=["1m", "5m 30s", "10m"],
      default_interval="10m",
  )

but it raises AttributeError('module 'marimo._plugins.ui' has no attribute 'refresh_button'')

Kind regards

### Your Suggestion for Changes

Doc improvement to change to marimo.ui.refresh (if I guess correctly)

### PR DESCRIPTION
**Pull request by scls19fr**
Closes #831

### CODE REVIEW

**Comment by mscolnick** [comment]
ah just saw this until now, i made the change as well https://github.com/marimo-team/marimo/pull/835

**Comment by scls19fr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by scls19fr** [comment]
No problem @mscolnick but maybe you should have add `refresh_button` for displaying button in this example

**Comment by mscolnick** [comment]
@scls19fr good call, thanks for the contrib!

**Pull request merged**
